version: '3'

services:
  db:
    container_name: coursework_db
    image: mysql:latest
    ports:
      - "5555:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coursework_db
      MYSQL_USER: user
      MYSQL_PASSWORD: root